// Copyright (c) 2014 DemonSquid, Inc. All rights reserved.

"use strict";

var NPC_MODEL = {
    /* SRD Primary Attributes */
    "Name": String,
    "CR": Number,
    "XP": Number,
    "Race": String,
    "MonsterSource": String,
    "Alignment": String,
    "Size": String,
    "Type": String,
    "SubType": String,
    "Init": String,
    "Senses": String,
    "Aura": String,
    "AC": String,
    "AC_Mods": String,
    "HP": Number,
    "HD": String,
    "HP_Mods": String,
    "Saves": String,
    "Fort": Number,
    "Ref": Number,
    "Will": Number,
    "Save_Mods": String,
    "DefensiveAbilities": String,
    "DR": String,
    "Immune": String,
    "Resist": String,
    "SR": String,
    "Weaknesses": String,
    "Speed": String,
    "Speed_Mod": String,
    "Melee": String,
    "Ranged": String,
    "Space": String,
    "Reach": String,
    "SpecialAttacks": String,
    "SpellLikeAbilities": String,
    "SpellsKnown": String,
    "SpellsPrepared": String,
    "SpellDomains": String,
    "BaseAtk": Number,
    "CMB": String,
    "CMD": String,
    "Feats": String,
    "Skills": String,
    "RacialMods": String,
    "Languages": String,
    "SQ": String,
    "Environment": String,
    "Organization": String,
    "Group": String,
    "Source": String,
    "SpecialAbilities": String,
    "Gender": String,
    "Bloodline": String,
    "ProhibitedSchools": String,
    "BeforeCombat": String,
    "DuringCombat": String,
    "Morale": String,
    "Gear": String,
    "OtherGear": String,
    "Vulnerability": String,
    "Note": String,
    "CharacterFlag": String,
    "CompanionFlag": String,
    "Fly": String,
    "Climb": String,
    "Burrow": String,
    "Swim": String,
    "Land": String,
    "TemplatesApplied": String,
    "OffenseNote": String,
    "BaseStatistics": String,
    "ExtractsPrepared": String,
    "AgeCategory": String,
    "Mystery": String,
    "ClassArchetypes": String,
    "Patron": String,
    "CompanionFamiliarLink": String,
    "FocusedSchool": String,
    "Traits": String,
    "AlternateNameForm": String,
    "LinkText": String,
    "UniqueMonster": String,
    "ThassilonianSpecialization": String,
    "Variant": String,
    "MR": Number,
    "Mythic": String,
    "MT": Number,
    /* Extra Computed Attributes */
    "id":String,
    "Description": String,
    "Description_Visual": String,
    "Str": Number,
    "Dex": Number,
    "Con": Number,
    "Int": Number,
    "Wis": Number,
    "Cha": Number,
    "Heroic": String,
    "Level": Number,
    "Classes": [
        {"Class": String, "Level": Number}
    ]
}


module.exports = function (mongoose) {
    return {
        NPC_ATTRIBUTES: Object.keys(NPC_MODEL),
        Npc: mongoose.model('Npc', NPC_MODEL)
    }
};

