'use strict';

DEMONSQUID.SOURCE_ABBREVIATIONS =
{
    "Academy Of Secrets": "AoS",
    "Advanced Player's Guide": "APG",
    "Advanced Race Guide": "ARG",
    "Andoran Spirit Of Liberty": "ASoL",
    "Andoran": "And",
    "Animal Archive": "AA",
    "Artifacts & Legends": "AL",
    "Bastards Of Golarion": "BoG",
    "Bestiary": "PB1",
    "Blood Of Angels": "BoA",
    "Blood Of Fiends": "BoF",
    "Blood Of The Moon": "BotM",
    "Blood Of The Night": "BotN",
    "Book of the Damned V1": "BDV1",
    "Book of the Damned V2": "BDV2",
    "Broken Chains": "BC",
    "Carrion Hill": "CH",
    "Castles Of The Inner Sea": "CotIS",
    "Champions Of Balance": "CoB",
    "Champions Of Purity": "CoP",
    "Cheliax Empire Of Devils": "CEoD",
    "Cheliax": "Chel",
    "Chronicle Of The Righteous": "CotR",
    "City Of Strangers": "CoS",
    "City of Golden Death": "CoGD",
    "City of Strangers": "CoS",
    "Classic Treasures": "CT",
    "ClassicHorrors": "CH",
    "Condition Cards": "CC",
    "Core Race": "CR",
    "Crypt Of The Everflame": "CotE",
    "Cult Of The Ebon Destroyers": "CotED",
    "Curse of the Riven Sky": "CotRS",
    "Demon Hunter's Handbook": "DHH",
    "Demons Revisited": "DR",
    "Distant Worlds": "DW",
    "Doom Comes To Dustpawn": "DCtD",
    "Dragon Empires Primer": "DEP",
    "Dragons Unleashed": "DU",
    "Dragonslayer's Handbook": "DH",
    "Dungeoneer's Handbook": "DH",
    "Dungeoneers Handbook": "DH",
    "Dungeons Of Golarion": "DoG",
    "Dwarves Of Golarion": "DoG",
    "Dwarves of Golarion": "DoG",
    "Faction Guide": "FG",
    "Faiths & Philosophies": "F&F",
    "Faiths Of Balance": "FoB",
    "Faiths Of Corruption": "FoC",
    "Faiths Of Purity": "FoP",
    "Fangwood Keep": "FK",
    "Fellnight Queen": "FQ",
    "Fey Revisited": "FR",
    "From Shore To Sea": "FStS",
    "From Shore to Sea": "FStS",
    "GameMastery Guide": "GG",
    "Giants Revisited": "GR",
    "Gnomes Of Golarion": "GoG",
    "Gnomes": "Gno",
    "Goblins Of Golarion": "GoG",
    "Godsmouth Heresy": "GH",
    "Halflings Of Golarion": "HoG",
    "Heart of the Jungle": "HJ",
    "Horsemen Of The Apocalypse": "HA",
    "Humans Of Golarion": "HoG",
    "Inner Sea Bestiary": "ISB",
    "Inner Sea Magic": "ISM",
    "Inner Sea NPC Codex": "ISNC",
    "Inner Sea World Guide": "ISWG",
    "Irrisen Land Of Eternal Winter": "ILEW",
    "Isles Of The Shackles": "IS",
    "Knights Of The Inner Sea": "KotIS",
    "Kobolds Of Golarion": "KoG",
    "Lands Of The Linnorm Kings": "LLK",
    "Lords Of Chaos": "LoC",
    "Lost Cities Of Golarion": "LCG",
    "Lost Kingdoms": "LK",
    "Magical Marketplace": "MM",
    "Magnimar City Of Monuments": "MCM",
    "Masks Of The Living God": "MLG",
    "Misfit Monsters Redeemed": "MMR",
    "Misfit Monsters": "MM",
    "Murder's Mark": "MM",
    "Mystery Monsters Revisited": "MMR",
    "Mythic Adventures": "MA",
    "Mythic Origins": "MO",
    "Mythic Realms": "MR",
    "Mythical Monsters Revisited": "MMR",
    "NPC Codex": "NC",
    "NPC Guide Web": "NGW",
    "NPC Guide": "NG",
    "No Response From Deepmar": "NRFD",
    "Orcs Of Golarion": "OoG",
    "Orcs of Golarion": "OoG",
    "Osirion, Legacy Of Pharaohs": "OLoP",
    "PFRPG Bestiary 2": "PB2",
    "PFRPG Bestiary 3": "PB3",
    "PFRPG Bestiary 4": "PB4",
    "PFRPG Bestiary": "PB1",
    "PFRPG Core": "Core",
    "PFS Pre Gen Download L1": "PFS",
    "PFS Pre Gen Download L4": "PFS",
    "PFS Pre Gen Download L7": "PFS",
    "PFS S0-05": "PFS",
    "PFS S1-29": "PFS",
    "PFS S1-30": "PFS",
    "PFS S1-31": "PFS",
    "PFS S1-32": "PFS",
    "PFS S1-33": "PFS",
    "PFS S1-34": "PFS",
    "PFS S1-35": "PFS",
    "PFS S1-36": "PFS",
    "PFS S1-37": "PFS",
    "PFS S1-38": "PFS",
    "PFS S1-39": "PFS",
    "PFS S1-40": "PFS",
    "PFS S1-41": "PFS",
    "PFS S1-42": "PFS",
    "PFS S1-43": "PFS",
    "PFS S1-44": "PFS",
    "PFS S1-45": "PFS",
    "PFS S1-46": "PFS",
    "PFS S1-47": "PFS",
    "PFS S1-48": "PFS",
    "PFS S1-49": "PFS",
    "PFS S1-50": "PFS",
    "PFS S1-51": "PFS",
    "PFS S1-52": "PFS",
    "PFS S1-53": "PFS",
    "PFS S1-54": "PFS",
    "PFS S1-55": "PFS",
    "PFS S1-56": "PFS",
    "PFS S2-01": "PFS",
    "PFS S2-02": "PFS",
    "PFS S2-03": "PFS",
    "PFS S2-04": "PFS",
    "PFS S2-05": "PFS",
    "PFS S2-06": "PFS",
    "PFS S2-07": "PFS",
    "PFS S2-08": "PFS",
    "PFS S2-09": "PFS",
    "PFS S2-10": "PFS",
    "PFS S2-11": "PFS",
    "PFS S2-12": "PFS",
    "PFS S2-13": "PFS",
    "PFS S2-14": "PFS",
    "PFS S2-15": "PFS",
    "PFS S2-16": "PFS",
    "PFS S2-17": "PFS",
    "PFS S2-18": "PFS",
    "PFS S2-19": "PFS",
    "PFS S2-20": "PFS",
    "PFS S2-21": "PFS",
    "PFS S2-22": "PFS",
    "PFS S3: Intro 1": "PFS",
    "PFS S3: Intro 2": "PFS",
    "PFS S3: Intro 3": "PFS",
    "Paizo Blog": "Blog",
    "Paizo Web Blog": "Blog",
    "Pathfinder Society Field Guide": "PFSFG",
    "Pathfinder Society Primer": "PFSP",
    "People Of The North": "PotN",
    "People Of The Sands": "PotS",
    "Pirates Of The Inner Sea": "PotIS",
    "Qadira": "Qad",
    "Quests and Campaigns": "QaC",
    "Rappan Athuk-Wilderness": "RAW",
    "Realm of the Fellnight Queen": "RotFQ",
    "Reign Of Winter Player's Guide": "RWPG",
    "Rival Gudie": "RG",
    "Rival Guide": "RG",
    "RotRL-AE-Appendix": "RotRL",
    "RotRL-AE-Fortress of the Stone Giants": "RotRL",
    "RotRL-AE-Hook Mountain Massacre": "RotRL",
    "RotRL-AE-Sins of the Saviors": "RotRL",
    "RotRL-AE-Spires of Xin-Shalast": "RotRL",
    "Sargava": "Sarg",
    "Seekers": "Seek",
    "Shatterd Star Web Suppliement": "SSWS",
    "Shattered Star Player's Guide": "SSPG",
    "The Dragon's Demand": "TDD",
    "The Feast Of Ravenmoor": "FR",
    "The Harrowing": "HAR",
    "The Midnight Mirror": "TMR",
    "The Moonscar": "Moon",
    "The Ruby Phoenix Tournament": "RPT",
    "The Witchwar Legacy": "WL",
    "The Worldwound": "TW",
    "Thornkeep": "Thorn",
    "Tomb Of The Iron Medusa": "TIM",
    "Tome of Horrors 4": "ToH",
    "Tome of Horrors Complete": "THC",
    "Tome of Horrors Revised": "THR",
    "Towns Of The Inner Sea": "TotIS",
    "Ultimate Campaign": "UCa",
    "Ultimate Combat": "UC",
    "Ultimate Equipment": "UE",
    "Ultimate Magic": "UM",
    "Undead Revisited": "UR",
    "Varisia": "Var",
    "Wardens Of The Reborn Forge": "WotRF",
    "We Be Goblins Too": "WBGT",
    "We Be Goblins!": "WBG",
    "Witch War": "WW",
    "d20pfsrd": "PFSRD",
    "fgfg": "?"
};

DEMONSQUID.encounterBuilderFilters.filter('abbreviateSource', function () {
    return function (source) {
        if (source && source.length <= 5) {
            return source;
        }
        return DEMONSQUID.SOURCE_ABBREVIATIONS[source] || "?";
    };
});

