"use strict";

var MONSTER_MODEL = {
    /* SRD Primary Attributes */
    "Name": String,
    "CR": Number,
    "XP": String,
    "Race": String,
    "MonsterSource": String,
    "Alignment": String,
    "Size": String,
    "Type": String,
    "SubType": String,
    "AC": String,
    "HP": String,
    "HD": String,
    "Saves": String,
    "Fort": String,
    "Ref": String,
    "Will": String,
    "Speed": String,
    "Melee": String,
    "Ranged": String,
    "Space": String,
    "Reach": String,
    "AbilityScores": String,
    "Feats": String,
    "Skills": String,
    "RacialMods": String,
    "Languages": String,
    "SQ": String,
    "Environment": String,
    "Organization": String,
    "Treasure": String,
    "Group": String,
    "Source": String,
    "IsTemplate": String,
    "CharacterFlag": String,
    "CompanionFlag": String,
    "Fly": String,
    "Climb": String,
    "Burrow": String,
    "Swim": String,
    "Land": String,
    "TemplatesApplied": String,
    "AgeCategory": String,
    "DontUseRacialHD": String,
    "VariantParent": String,
    "CompanionFamiliarLink": String,
    "AlternateNameForm": String,
    "UniqueMonster": String,
    "MR": String,
    "Mythic": Boolean,
    "MT": String,
    /* Extra Computed Attributes */
    "Description": String,
    "Description_Visual": String,
    "Init": String,
    "Senses": String,
    "SR": String,
    "DR": String,
    "Immune": String,
    "Resist": String,
    "Weaknesses": String,
    "SpecialAttacks": String,
    "SpellLikeAbilities": String,
    "Str": String,
    "Dex": String,
    "Con": String,
    "Int": String,
    "Wis": String,
    "Cha": String,
    "BaseAtk": String,
    "CMB": String,
    "CMD": String,
    "SpecialAbilities": String,
    "TreasureBudget": String,
    "Heroic": Boolean,
    "Level": String,
    "Classes": [
        {"Class": String, "Level": Number}
    ],
    "ACDetails":String
};

module.exports = function (mongoose) {
    return {
        MONSTER_ATTRIBUTES : Object.keys(MONSTER_MODEL),
        Monster :  mongoose.model('Monster', MONSTER_MODEL)
    }
};